version: "3"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - 27017:27017

  springwebfluxdemo:
    image: springwebfluxdemo
    ports:
      - 8090:8090
    links:
      - mongo